#设置数据源
spring:
  datasource:
    username: root
    password: root
#    password: 123456
    url: jdbc:mysql://localhost:3307/springbootblog?useSSL=false
#    url: jdbc:mysql://localhost:3306/springbootblog?useSSL=false
    #连接池配置
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  # 去除thymeleaf缓存
  thymeleaf:
    cache: false
#    #thymeleaf
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: LEGACYHTML5
#    encoding: UTF-8
#    content-type: text/html

server:
  port: 8090

#server:
#  port: 80

mybatis:
#  指定映射文件目录
  mapper-locations: classpath:com/jiangjiawei/dao/*.xml
#  设置包别名
  type-aliases-package: com.jiangjiawei.domain
#  控制台查看sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

