package com.jiangjiawei.domain;

import lombok.AllArgsConstructor;

import java.util.Date;

/**
 * columnist
 * 
 * @author jjw
 * @version 1.0.0 2020-08-22
 */

@AllArgsConstructor
public class Columnist implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -2044821228764207912L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 专栏ID */
    private Integer id;

    /** 分类名称 */
    private String name;

    /** 简介 */
    private String info;

    /** 博客数量 */
    private Integer blogCount;

    /** 专栏状态 0 删除 1 使用中*/
    private Integer state;

    /** 创建时间 */
    private Date createTime;

    /** 更新时间 */
    private Date updateTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取专栏ID
     * 
     * @return 专栏ID
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置专栏ID
     * 
     * @param id
     *          专栏ID
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取分类名称
     * 
     * @return 分类名称
     */
    public String getName() {
        return this.name;
    }

    /**
     * 设置分类名称
     * 
     * @param name
     *          分类名称
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取简介
     * 
     * @return 简介
     */
    public String getInfo() {
        return this.info;
    }

    /**
     * 设置简介
     * 
     * @param info
     *          简介
     */
    public void setInfo(String info) {
        this.info = info;
    }

    /**
     * 获取博客数量
     * 
     * @return 博客数量
     */
    public Integer getBlogCount() {
        return this.blogCount;
    }

    /**
     * 设置博客数量
     * 
     * @param blogCount
     *          博客数量
     */
    public void setBlogCount(Integer blogCount) {
        this.blogCount = blogCount;
    }

    /**
     * 获取创建时间
     * 
     * @return 创建时间
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置创建时间
     * 
     * @param createTime
     *          创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        return "Columnist{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", info='" + info + '\'' +
                ", blogCount=" + blogCount +
                ", state=" + state +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                '}';
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}