package com.jiangjiawei.domain;

import java.util.Date;

/**
 * comment
 * 
 * @author jjw
 * @version 1.0.0 2020-08-22
 */
public class Comment implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -9150525716423738213L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 评论ID */
    private Integer id;

    /** 留言人名称 */
    private String replyName;

    /** 留言人邮箱 */
    private String replyEmail;

    /** 评论博客ID */
    private Integer blogId;

    /** 发布时间 */
    private Date publishDate;

    /** 是否是博主 */
    private String bloggerState;

    /** 留言状态 */
    private String replyState;

    /** 留言内容 */
    private String replyContent;

    /** 父留言ID */
    private Integer parentId;

    /** 评论创建时间 */
    private Date createTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取评论ID
     * 
     * @return 评论ID
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置评论ID
     * 
     * @param id
     *          评论ID
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取留言人名称
     * 
     * @return 留言人名称
     */
    public String getReplyName() {
        return this.replyName;
    }

    /**
     * 设置留言人名称
     * 
     * @param replyName
     *          留言人名称
     */
    public void setReplyName(String replyName) {
        this.replyName = replyName;
    }

    /**
     * 获取留言人邮箱
     * 
     * @return 留言人邮箱
     */
    public String getReplyEmail() {
        return this.replyEmail;
    }

    /**
     * 设置留言人邮箱
     * 
     * @param replyEmail
     *          留言人邮箱
     */
    public void setReplyEmail(String replyEmail) {
        this.replyEmail = replyEmail;
    }

    /**
     * 获取评论博客ID
     * 
     * @return 评论博客ID
     */
    public Integer getBlogId() {
        return this.blogId;
    }

    /**
     * 设置评论博客ID
     * 
     * @param blogId
     *          评论博客ID
     */
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }

    /**
     * 获取发布时间
     * 
     * @return 发布时间
     */
    public Date getPublishDate() {
        return this.publishDate;
    }

    /**
     * 设置发布时间
     * 
     * @param publishDate
     *          发布时间
     */
    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }

    /**
     * 获取是否是博主
     * 
     * @return 是否是博主
     */
    public String getBloggerState() {
        return this.bloggerState;
    }

    /**
     * 设置是否是博主
     * 
     * @param bloggerState
     *          是否是博主
     */
    public void setBloggerState(String bloggerState) {
        this.bloggerState = bloggerState;
    }

    /**
     * 获取留言状态
     * 
     * @return 留言状态
     */
    public String getReplyState() {
        return this.replyState;
    }

    /**
     * 设置留言状态
     * 
     * @param replyState
     *          留言状态
     */
    public void setReplyState(String replyState) {
        this.replyState = replyState;
    }

    /**
     * 获取留言内容
     * 
     * @return 留言内容
     */
    public String getReplyContent() {
        return this.replyContent;
    }

    /**
     * 设置留言内容
     * 
     * @param replyContent
     *          留言内容
     */
    public void setReplyContent(String replyContent) {
        this.replyContent = replyContent;
    }

    /**
     * 获取父留言ID
     * 
     * @return 父留言ID
     */
    public Integer getParentId() {
        return this.parentId;
    }

    /**
     * 设置父留言ID
     * 
     * @param parentId
     *          父留言ID
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * 获取评论创建时间
     * 
     * @return 评论创建时间
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置评论创建时间
     * 
     * @param createTime
     *          评论创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}