package com.jiangjiawei.domain;

import lombok.AllArgsConstructor;

import java.util.Date;

/**
 * user
 * 
 * @author jjw
 * @version 1.0.0 2020-08-22
 */

@AllArgsConstructor
public class User implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -6408962860089881730L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 用户ID */
    private Integer id;

    /** 电子邮箱 */
    private String emial;

    /** 用户名称 */
    private String name;

    /** 密码 */
    private String password;

    /** 用户头像地址 */
    private String icon;

    /** 是否是管理员 */
    private Integer admin;

    /** 创建时间 */
    private Date createTime;

    /** 性别 */
    private String sex;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取用户ID
     * 
     * @return 用户ID
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置用户ID
     * 
     * @param id
     *          用户ID
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取电子邮箱
     * 
     * @return 电子邮箱
     */
    public String getEmial() {
        return this.emial;
    }

    /**
     * 设置电子邮箱
     * 
     * @param emial
     *          电子邮箱
     */
    public void setEmial(String emial) {
        this.emial = emial;
    }

    /**
     * 获取用户名称
     * 
     * @return 用户名称
     */
    public String getName() {
        return this.name;
    }

    /**
     * 设置用户名称
     * 
     * @param name
     *          用户名称
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取密码
     * 
     * @return 密码
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * 设置密码
     * 
     * @param password
     *          密码
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * 获取用户头像地址
     * 
     * @return 用户头像地址
     */
    public String getIcon() {
        return this.icon;
    }

    /**
     * 设置用户头像地址
     * 
     * @param icon
     *          用户头像地址
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * 获取是否是管理员
     * 
     * @return 是否是管理员
     */
    public Integer getAdmin() {
        return this.admin;
    }

    /**
     * 设置是否是管理员
     * 
     * @param admin
     *          是否是管理员
     */
    public void setAdmin(Integer admin) {
        this.admin = admin;
    }

    /**
     * 获取创建时间
     * 
     * @return 创建时间
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置创建时间
     * 
     * @param createTime
     *          创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取性别
     * 
     * @return 性别
     */
    public String getSex() {
        return this.sex;
    }

    /**
     * 设置性别
     * 
     * @param sex
     *          性别
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /* This code was generated by TableGo tools, mark 2 end. */

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", emial='" + emial + '\'' +
                ", name='" + name + '\'' +
                ", password='" + password + '\'' +
                ", icon='" + icon + '\'' +
                ", admin=" + admin +
                ", createTime=" + createTime +
                ", sex='" + sex + '\'' +
                '}';
    }
}